version: '3.1'

services:

  wordpress-container:
    image: wordpress
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_HOST=mysql-container
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
